[package]
name = "jpeg_viewer"
version = "0.1.4"
edition = "2024"

[dependencies]
eframe = "0.33" # do not update this one!
egui = "0.35.0"
image = { version = "0.25.10", features = ["default-formats"] }
rayon = "1.12.0"
rfd = "0.17.2"
pollster = "1.0.1"
rust-ini = "0.21.3"
zip = "8.6.0"
sevenz-rust2 = "0.21.4"
unrar = "0.5"
trash = "5.2.6"
natord = "1.0"
gif = "0.14.2"
lru = "0.18.2"  # for LRU cache
dirs = "6.0.0"
rand = "0.8" # do not update this one!
open = "5.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

[target.'cfg(target_os = "macos")'.build-dependencies]

[target.'cfg(target_os = "linux")'.build-dependencies]

